// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("webapi.Data.Models.Clan", b =>
                {
                    b.Property<int>("ClanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTotem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClanID");

                    b.ToTable("Clan");

                    b.HasData(
                        new
                        {
                            ClanID = 1,
                            Name = "Njovu",
                            SubTotem = "Hippopotamus",
                            Symbol = "Elephant"
                        },
                        new
                        {
                            ClanID = 2,
                            Name = "Clan2",
                            SubTotem = "Hippopotamus",
                            Symbol = "Elephant"
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.ClanHouse", b =>
                {
                    b.Property<int>("ClanHouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClanHouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClanID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClanHouseID");

                    b.HasIndex("ClanID");

                    b.ToTable("ClanHouse");

                    b.HasData(
                        new
                        {
                            ClanHouseID = 1,
                            ClanHouseName = "FirstClanHouse",
                            ClanID = 1
                        },
                        new
                        {
                            ClanHouseID = 2,
                            ClanHouseName = "SecondClanHouse",
                            ClanID = 1
                        },
                        new
                        {
                            ClanHouseID = 3,
                            ClanHouseName = "ThirdHouse",
                            ClanID = 2
                        },
                        new
                        {
                            ClanHouseID = 4,
                            ClanHouseName = "FourthHouse",
                            ClanID = 2
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenderID");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            GenderCode = "M",
                            GenderValue = "Male"
                        },
                        new
                        {
                            GenderID = 2,
                            GenderCode = "F",
                            GenderValue = "Female"
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClanHouseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grandparents")
                        .HasColumnType("TEXT");

                    b.Property<string>("GreatGrandparents")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterPara")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.HasIndex("GenderID");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Address = "123 Unknown Street",
                            BirthDate = "01/1970",
                            City = "Johanesburg",
                            ClanHouseID = 0,
                            Email = "kenny@unknown.com",
                            FirstName = "Kenneth",
                            GenderID = 1,
                            IsActive = true,
                            IsUser = true,
                            LastName = "Odombe",
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 510, DateTimeKind.Local).AddTicks(9874),
                            LoginId = "kenny",
                            MiddleName = "R",
                            Password = "1234",
                            Telephone = "1234567890"
                        },
                        new
                        {
                            PersonID = 2,
                            Address = "123 Unknown Street",
                            BirthDate = "01/1970",
                            City = "Johanesburg",
                            ClanHouseID = 1,
                            Email = "kenny@unknown.com",
                            FirstName = "House",
                            GenderID = 1,
                            IsActive = true,
                            IsUser = true,
                            LastName = "First",
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 510, DateTimeKind.Local).AddTicks(9994),
                            LoginId = "firsthouse",
                            MiddleName = "Clan",
                            Password = "1234",
                            Telephone = "1234567890"
                        },
                        new
                        {
                            PersonID = 3,
                            Address = "123 Unknown Street",
                            BirthDate = "01/1970",
                            City = "Johanesburg",
                            ClanHouseID = 2,
                            Email = "kenny@unknown.com",
                            FirstName = "House",
                            GenderID = 1,
                            IsActive = true,
                            IsUser = true,
                            LastName = "Second",
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 511, DateTimeKind.Local).AddTicks(9),
                            LoginId = "secondhouse",
                            MiddleName = "Clan",
                            Password = "1234",
                            Telephone = "1234567890"
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.PersonClanHouseRequest", b =>
                {
                    b.Property<int>("PersonClanHouseRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanHouseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonClanHouseRequestID");

                    b.HasIndex("ClanHouseID");

                    b.HasIndex("PersonID");

                    b.HasIndex("RequestTypeID");

                    b.ToTable("PersonClanHouseRequest");
                });

            modelBuilder.Entity("webapi.Data.Models.PersonRole", b =>
                {
                    b.Property<int>("PersonRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonRoleID");

                    b.HasIndex("PersonID");

                    b.HasIndex("RoleID");

                    b.ToTable("PersonRole");

                    b.HasData(
                        new
                        {
                            PersonRoleID = 1,
                            IsActive = true,
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 511, DateTimeKind.Local).AddTicks(70),
                            PersonID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            PersonRoleID = 2,
                            IsActive = true,
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 511, DateTimeKind.Local).AddTicks(81),
                            PersonID = 2,
                            RoleID = 3
                        },
                        new
                        {
                            PersonRoleID = 3,
                            IsActive = true,
                            LastUpdatedBy = "Kenneth R Odombe",
                            LastUpdatedDate = new DateTime(2023, 6, 11, 22, 39, 9, 511, DateTimeKind.Local).AddTicks(91),
                            PersonID = 3,
                            RoleID = 3
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.RequestType", b =>
                {
                    b.Property<int>("RequestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("RequestTypeValue")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("RequestTypeID");

                    b.ToTable("RequestType");

                    b.HasData(
                        new
                        {
                            RequestTypeID = 1,
                            RequestTypeCode = "R",
                            RequestTypeValue = "Requested"
                        },
                        new
                        {
                            RequestTypeID = 2,
                            RequestTypeCode = "A",
                            RequestTypeValue = "Approved"
                        },
                        new
                        {
                            RequestTypeID = 3,
                            RequestTypeCode = "D",
                            RequestTypeValue = "Declined"
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleDesc = "Admin role",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleDesc = "User role",
                            RoleName = "User"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleDesc = "Clan Leader role",
                            RoleName = "Clan Leader"
                        });
                });

            modelBuilder.Entity("webapi.Data.Models.ClanHouse", b =>
                {
                    b.HasOne("webapi.Data.Models.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("webapi.Data.Models.Person", b =>
                {
                    b.HasOne("webapi.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("webapi.Data.Models.PersonClanHouseRequest", b =>
                {
                    b.HasOne("webapi.Data.Models.ClanHouse", "ClanHouse")
                        .WithMany()
                        .HasForeignKey("ClanHouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Data.Models.Person", "Person")
                        .WithMany("PersonClanHouseRequests")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Data.Models.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanHouse");

                    b.Navigation("Person");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("webapi.Data.Models.PersonRole", b =>
                {
                    b.HasOne("webapi.Data.Models.Person", "Person")
                        .WithMany("PersonRoles")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Data.Models.Role", "Role")
                        .WithMany("PersonRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("webapi.Data.Models.Person", b =>
                {
                    b.Navigation("PersonClanHouseRequests");

                    b.Navigation("PersonRoles");
                });

            modelBuilder.Entity("webapi.Data.Models.Role", b =>
                {
                    b.Navigation("PersonRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
